"""Add PYQ subject-level entity, remove PYQ material type

Revision ID: 2f6c01170f1f
Revises: 4abca63218a4
Create Date: 2026-07-04 19:40:32.886919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f6c01170f1f'
down_revision: Union[str, Sequence[str], None] = '4abca63218a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pyqs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('exam_type', sa.Enum('End Sem', 'TT1', 'TT2', name='exam_type'), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # --- hand-written: migrate existing type='PYQ' materials into the new
    # subject-level pyqs table before the type value is removed. Best-effort
    # parse of exam type / year from the old free-text title.
    op.execute(
        """
        INSERT INTO pyqs (subject_id, exam_type, year, file_url)
        SELECT
            COALESCE(mod.subject_id, exp.subject_id),
            (CASE
                WHEN m.title ILIKE '%TT1%' THEN 'TT1'
                WHEN m.title ILIKE '%TT2%' THEN 'TT2'
                ELSE 'End Sem'
            END)::exam_type,
            COALESCE((regexp_match(m.title, '(20\\d{2})'))[1]::int, EXTRACT(year FROM now())::int),
            m.file_url
        FROM materials m
        LEFT JOIN modules mod ON m.module_id = mod.id
        LEFT JOIN experiments exp ON m.experiment_id = exp.id
        WHERE m.type = 'PYQ'
        """
    )
    op.execute("DELETE FROM materials WHERE type = 'PYQ'")

    # Postgres has no ALTER TYPE ... DROP VALUE, so the enum must be recreated.
    op.execute("ALTER TYPE material_type RENAME TO material_type_old")
    op.execute(
        "CREATE TYPE material_type AS ENUM "
        "('Notes', 'Short Notes', 'PPT', 'Textbook', 'Lab Manual', 'Practical Code')"
    )
    op.execute(
        "ALTER TABLE materials ALTER COLUMN type TYPE material_type USING type::text::material_type"
    )
    op.execute("DROP TYPE material_type_old")


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("ALTER TYPE material_type RENAME TO material_type_new")
    op.execute(
        "CREATE TYPE material_type AS ENUM "
        "('PYQ', 'Notes', 'Short Notes', 'PPT', 'Textbook', 'Lab Manual', 'Practical Code')"
    )
    op.execute(
        "ALTER TABLE materials ALTER COLUMN type TYPE material_type USING type::text::material_type"
    )
    op.execute("DROP TYPE material_type_new")

    # Note: pyqs rows are not converted back into materials rows on downgrade.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pyqs')
    # ### end Alembic commands ###
