"""Add practical labs support

Revision ID: 66b749355beb
Revises: cb1573593edc
Create Date: 2026-07-04 17:09:12.298801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66b749355beb'
down_revision: Union[str, Sequence[str], None] = 'cb1573593edc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('materials', sa.Column('experiment_id', sa.Integer(), nullable=True))
    op.alter_column('materials', 'module_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'materials', 'experiments', ['experiment_id'], ['id'])
    op.add_column('subjects', sa.Column('has_theory', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('subjects', sa.Column('has_lab', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###

    # --- hand-written: not picked up by autogenerate ---
    op.execute("ALTER TYPE material_type ADD VALUE IF NOT EXISTS 'Lab Manual'")
    op.execute("ALTER TYPE material_type ADD VALUE IF NOT EXISTS 'Practical Code'")

    op.create_check_constraint(
        "ck_materials_module_xor_experiment",
        "materials",
        "(module_id IS NOT NULL AND experiment_id IS NULL) "
        "OR (module_id IS NULL AND experiment_id IS NOT NULL)",
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Postgres cannot drop enum values without recreating the type; the
    # 'Lab Manual' / 'Practical Code' labels are left in place on downgrade.
    op.drop_constraint("ck_materials_module_xor_experiment", "materials", type_="check")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subjects', 'has_lab')
    op.drop_column('subjects', 'has_theory')
    op.drop_constraint(None, 'materials', type_='foreignkey')
    op.alter_column('materials', 'module_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('materials', 'experiment_id')
    op.drop_table('experiments')
    # ### end Alembic commands ###
